version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
    environment:
      - BASE_URL=http://server:3000
    image: habitica
    networks:
      - habitica
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/habitica
      - /usr/src/habitica/node_modules
      - /usr/src/habitica/website/client/node_modules
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      # test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 60s
      retries: 5
      timeout: 10s
  server:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "start"]
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    image: habitica
    networks:
      - habitica
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/habitica
      - /usr/src/habitica/node_modules
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
  mongo:
    image: mongo:3.6
    networks:
      - habitica
    ports:
      - "27017:27017"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/usr/src/habitica/prometheus/prometheus.yml
    command:
      - '--config.file=/usr/src/habitica/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=illchangeitanyway
    depends_on:
      - prometheus
    ports:
      - '9095:9095'

networks:
  habitica:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
