scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s

    static_configs:
      - targets: [
          'localhost:9090',
      ]
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'
